name: Zabbix
description: |
  Zabbix is an enterprise-class open source distributed monitoring solution.
version: "0.0.0"
category: Web
maintainer: Greg Newton
license: GNU General Public License (GPL) version 2
projectURL: https://www.zabbix.com/
