name: Zabbix
description: |
  Zabbix is an enterprise-class open source distributed monitoring solution.
version: "0.1.0"
category: Web
maintainer: Greg Newton
license: Apache, v2
projectURL: https://www.zabbix.com/
